# Generated by Django 4.2.7 on 2023-12-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('breed', models.CharField(blank=True, max_length=45, null=True)),
                ('species', models.CharField(blank=True, max_length=5, null=True)),
                ('sex', models.CharField(blank=True, max_length=6, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
                ('vaccinations', models.IntegerField(blank=True, null=True)),
                ('sterilization', models.IntegerField(blank=True, null=True)),
                ('friendly_kids', models.IntegerField(blank=True, null=True)),
                ('friendly_others', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('idworker', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
