# Generated by Django 4.2.7 on 2023-12-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_animals_vaccinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='friendly_kids',
            field=models.IntegerField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='friendly_others',
            field=models.IntegerField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='sterilization',
            field=models.IntegerField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
