# Generated by Django 4.2.7 on 2023-12-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_animals_friendly_kids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Big', 'Big')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='species',
            field=models.CharField(blank=True, choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='status',
            field=models.CharField(blank=True, choices=[('For adoption', 'For adoption'), ('Not available', 'Not available')], max_length=20, null=True),
        ),
    ]
