# Generated by Django 4.2.7 on 2023-12-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_animals_sex_alter_animals_size_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animals',
            new_name='Animal',
        ),
    ]
