# Generated by Django 4.2.7 on 2023-12-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_animal_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id_connector', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.animal')),
            ],
        ),
    ]
