# Generated by Django 4.2.7 on 2023-12-06 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_idworker_workers_id_worker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopt_form',
            fields=[
                ('id_adopt_form', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=9, null=True)),
                ('id_adoptee', models.IntegerField(help_text='Please enter the ID of the animal you are interested in', max_length=5, null=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.animal')),
            ],
        ),
        migrations.AddField(
            model_name='connector',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.workers'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='animal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.animal'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Adoption_history',
            fields=[
                ('id_adoption_history', models.AutoField(primary_key=True, serialize=False)),
                ('form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.adopt_form')),
            ],
        ),
    ]
