# Generated by Django 4.2.7 on 2023-12-07 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
