# Generated by Django 4.2.7 on 2023-12-10 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='surname',
        ),
        migrations.AlterField(
            model_name='adoption_history',
            name='form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.adopt_form'),
        ),
    ]
