# Generated by Django 4.2.7 on 2023-12-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_workers_name_remove_workers_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
