# Generated by Django 4.2.7 on 2023-12-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_adopt_form_status_alter_adopt_form_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopt_form',
            name='id_adoptee',
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='friendly_kids',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Friendly to kids'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='friendly_others',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Friendly to other animals'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sterilization',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Sterilized'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccinations',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Vaccinated'),
        ),
    ]
