# Generated by Django 4.2.7 on 2024-01-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_animal_friendly_kids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='img',
            field=models.ImageField(default='pfp2.jpg', upload_to='animal_pics/'),
        ),
    ]
